# Generated by Django 4.2.5 on 2024-01-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_imge_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imge',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
